[build]
  base    = "client"
  publish = "client/build"
  command = "npm run build --prefix client"

[dev]  
  publish = "client/build"
  command = "npm start --prefix client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
